---
# The address on which VBMC will listen for IPMI traffic for this domain.
vbmc_ipmi_address:
# The port on which VBMC will listen for IPMI traffic for this domain.
vbmc_ipmi_port:
# The IPMI username that VBMC will use.
vbmc_ipmi_username:
# The IPMI password that VBMC will use.
vbmc_ipmi_password:
# The name of the Libvirt domain to be added to Virtual BMC.
vbmc_domain:
# The directory in which to store VBMC logs.
vbmc_log_directory:
# The path to the virtualenv in which Virtual BMC is installed.
vbmc_virtualenv_path:
# Whether the domain should be `present` or `absent` in Virtual BMC.
vbmc_state: present
# libvirt connnection URI
vbmc_libvirt_uri:
